#!/bin/bash

if [ `hostname` = "wanderlust.local" ]; then
  echo "Building on wanderlust.local ..."
  ./Setup.lhs configure --user --prefix=/Users/arjun/local && \
  ./Setup.lhs build
elif [ `hostname` = "sharpe" ]; then
  echo "Building on sharpe for /course/cs173/testfest"
  ./Setup.lhs configure --user --prefix=/course/cs173/testfest && \
  ./Setup.lhs build
  ./Setup.lhs install

else
  echo "ERROR: Don't know how to build on " `hostname`
fi
