#!/bin/bash

if [ `hostname` = "wanderlust.local" ]; then
  echo "Building on wanderlust.local ..."
  ./Setup.lhs configure --user --prefix=/Users/arjun/local && \
  ./Setup.lhs build
elif [ `hostname` = "peabody" ]; then
  echo "Building on peabody for deployment to cs173"
  ./Setup.lhs configure --user --prefix=/tourney && \
  ./Setup.lhs build
  ./Setup.lhs copy --destdir=cs173

else
  echo "ERROR: Don't know how to build on " `hostname`
fi
